### ISSUE TITLE
Fix country-language dependency

### ISSUE THREAD

**Issue by jeremydw** [blinkk/fileset#29]
The country-language dependency must be loaded via git rather than npm:
https://github.com/blinkk/fileset/blob/main/package.json#L83

The maintainer has not replied on the issue: https://github.com/bdswiss/country-language/issues/17

The GitHub Action is struggling with loading it via git: 
https://github.com/blinkk/fileset/runs/4075178948?check_suite_focus=true

**Comment by jeremydw** [comment]
@stevenle Thoughts on fixing this?

**Comment by stevenle** [comment]
I don't get why they even use underscore. Seems like all they're doing is reading data from a JSON file. Can we just use their data.json here?

**Comment by jeremydw** [comment]
Maybe we fork their repo and release our own version that:
- Abandons underscore
- Converts the CSV to JSON so CSVs don't have to be parsed
- Uses conventional commits, best practices, etc.
Thoughts?

**Comment by stevenle** [comment]
I could be wrong but I think their csvs are already converted to JSON in https://github.com/bdswiss/country-language/blob/master/data.json. I think we just need that file, and we can write our own code to extract the data we need.

**Comment by stevenle** [comment]
FYI I was able to remove Oak's dep on country-language in: https://github.com/blinkk/oak/commit/4076cfe5060683964d5ea7776281a7e7213b4b51

**Comment by jeremydw** [comment]
Thanks, just took the same approach and fixed it in https://github.com/blinkk/fileset/commit/dedf2c46d00ff6c534ac310247ff260923b8c5d8
